/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecyo_progra_3.Presentation;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import proyecyo_progra_3.Domain.Ports.Input.VisualizarEstadisticasUseCase;
import proyecyo_progra_3.Infraestructure.Config.ApplicationContainer;

/**
 *
 * @author Usuario
 */
public class FrmEstadisticas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmEstadisticas.class.getName());
    private final ApplicationContainer appContainer = ApplicationContainer.getInstance();
    
    private final VisualizarEstadisticasUseCase estadisticasUseCase = appContainer.getVisualizarEstadisticas();
    
    
    private JPanel pnlGraficoLinea;
    private JPanel pnlGraficoPastel;
    
    
    /**
     * Creates new form FrmEstadisticas
     */
    public FrmEstadisticas() {
        initComponents();
        
        inicializarVentana();
        cargarGraficos();
    }

    
    
    private void inicializarVentana() {
        setTitle("Dashboard de Estadísticas - Sistema de Riego");
        setSize(900, 500);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Solo cierra esta ventana, no la app
        setLocationRelativeTo(null);
        setLayout(new GridLayout(1, 2, 10, 10)); // Divide la ventana en 2 columnas

        pnlGraficoLinea = new JPanel(new BorderLayout());
        pnlGraficoPastel = new JPanel(new BorderLayout());

        add(pnlGraficoLinea);
        add(pnlGraficoPastel);
    }

    public void cargarGraficos() {
       
        Map<String, Double> datosHumedad = estadisticasUseCase.obtenerDatosHumedadHistorica();
        DefaultCategoryDataset datasetLinea = new DefaultCategoryDataset();
        
        for (Map.Entry<String, Double> entry : datosHumedad.entrySet()) {
            datasetLinea.addValue(entry.getValue(), "Humedad (%)", entry.getKey());
        }

        JFreeChart chartLinea = ChartFactory.createLineChart(
                "Promedio de Humedad Hoy",  
                "Hora del Día",             
                "Humedad (%)",              
                datasetLinea
        );

        ChartPanel panelChartLinea = new ChartPanel(chartLinea);
        pnlGraficoLinea.removeAll();
        pnlGraficoLinea.add(panelChartLinea, BorderLayout.CENTER);
        pnlGraficoLinea.validate();

        // --- 2. GRÁFICO DE PASTEL (Modos de Riego) ---
        Map<String, Integer> datosModos = estadisticasUseCase.obtenerDatosModosRiego();
        DefaultPieDataset datasetPastel = new DefaultPieDataset();
        
        for (Map.Entry<String, Integer> entry : datosModos.entrySet()) {
            datasetPastel.setValue(entry.getKey(), entry.getValue());
        }

        JFreeChart chartPastel = ChartFactory.createPieChart(
                "Distribución de Modos de Riego", 
                datasetPastel,
                true,  
                true,  
                false  
        );

        ChartPanel panelChartPastel = new ChartPanel(chartPastel);
        pnlGraficoPastel.removeAll();
        pnlGraficoPastel.add(panelChartPastel, BorderLayout.CENTER);
        pnlGraficoPastel.validate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmEstadisticas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
