/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecyo_progra_3.Presentation;

import javax.swing.*;

import proyecyo_progra_3.Applicaction.Service.ConectarESP32Interactor;
import proyecyo_progra_3.Applicaction.Service.IniciarRiegoInteractor;
import proyecyo_progra_3.Domain.Service.SistemaRiegoService;
import proyecyo_progra_3.Infraestructure.Config.ApplicationContainer;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Usuario
 */
public class FrmPanelRiego extends JFrame {
    
    private static final Logger logger = Logger.getLogger(FrmPanelRiego.class.getName());
    
    private final ApplicationContainer appContainer = ApplicationContainer.getInstance();
    private final IniciarRiegoInteractor iniciarRiegoInteractor = appContainer.getIniciarRiegoInteractor();
    private final ConectarESP32Interactor conectarESP32 = appContainer.getConectarESP32Interactor();


    private SistemaRiegoService servicio;

    /**
     * Creates new form FrmPanelRiego
     */

    public FrmPanelRiego() {
        initComponents();

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        btnIniciarRiegoAutomatico = new JButton();
        btnVolverMenu = new JButton();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        btnConectar = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sistema de Riego");

        jLabel2.setText("Iniciar Riego");

        btnIniciarRiegoAutomatico.setText("Iniciar Riego");
        btnIniciarRiegoAutomatico.addActionListener(this::btnIniciarRiegoAutomaticoActionPerformed);

        btnVolverMenu.setText("Volver al Menú");
        btnVolverMenu.addActionListener(this::btnVolverMenuActionPerformed);

        jLabel4.setText("Sistema de Riego Automatico");

        jLabel5.setText("Sistema de Riego Manual");

        btnConectar.setText("Conectar");
        btnConectar.addActionListener(this::btnConectarActionPerformed);

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnVolverMenu, GroupLayout.PREFERRED_SIZE, 117, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 189, GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(btnIniciarRiegoAutomatico, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(btnConectar, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 186, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(292, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIniciarRiegoAutomatico, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnConectar, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE)))
                .addGap(193, 193, 193)
                .addComponent(jLabel5)
                .addGap(117, 117, 117)
                .addComponent(btnVolverMenu, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarRiegoAutomaticoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnIniciarRiegoAutomaticoActionPerformed
        // TODO add your handling code here:


        
    
/*
        if (!servicio.estaConectado()) {
            JOptionPane.showMessageDialog(this, "Conéctese al ESP32 primero");
            return;
        }

        if (!servicio.getTanque().tieneAgua()) {
            JOptionPane.showMessageDialog(this, "Tanque vacío");
            return;
        }

  
        String resultado = servicio.iniciarRiego();
        JOptionPane.showMessageDialog(this, resultado);
        */
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnIniciarRiegoAutomaticoActionPerformed

    private void btnVolverMenuActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
        // TODO add your handling code here:}

        FrmMenu frm = new FrmMenu();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverMenuActionPerformed

    private void btnConectarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed


        String puerto = JOptionPane.showInputDialog("Indique el puerto:");

        boolean conectado = conectarESP32.ejecutar(puerto);

        
        if (puerto == null || puerto.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar un nombre de puerto válido.");
                return; 
        }
        
        if (!conectado) {
            JOptionPane.showMessageDialog(this, "Error al conectar");
            btnIniciarRiegoAutomatico.setEnabled(false);
            return;
        }
        
        


        JOptionPane.showMessageDialog(this, "Conectado");

    }//GEN-LAST:event_btnConectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | UnsupportedLookAndFeelException ex) {
            logger.log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(() -> new FrmPanelRiego().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnConectar;
    private JButton btnIniciarRiegoAutomatico;
    private JButton btnVolverMenu;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
