/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecyo_progra_3.Presentation;

import javax.swing.JOptionPane;
import proyecyo_progra_3.Applicaction.Service.ConectarESP32Interactor;
import proyecyo_progra_3.Domain.Ports.Input.DetenerRiegoUseCase;
import proyecyo_progra_3.Domain.Ports.Input.IniciarRiegoUseCase;
import proyecyo_progra_3.Infraestructure.Config.ApplicationContainer;

/**
 *
 * @author Usuario
 */
public class FrmPanelRiegoManual extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPanelRiegoManual.class.getName());
    
    
    private final ApplicationContainer appContainer = ApplicationContainer.getInstance();
    private final IniciarRiegoUseCase iniciarRiego = appContainer.getIniciarRiegoInteractor();
    private final DetenerRiegoUseCase detenerRiego = appContainer.getDetenerRiegoInteractor();
    private final ConectarESP32Interactor conectarESP32 = appContainer.getConectarESP32Interactor();
    

    
    
    /**
     * Creates new form FrmPanelRiegoManual
     */
    public FrmPanelRiegoManual() {
        initComponents();
        
        btnIniciarRiegoManual.setEnabled(false);
        btnDetenerRiegoManual.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDetenerRiegoManual = new javax.swing.JButton();
        btnIniciarRiegoManual = new javax.swing.JButton();
        btnVolverAlMenu = new javax.swing.JButton();
        btnConectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sistemas de Riego");

        jLabel2.setText("Sistema de Riego Manual");

        btnDetenerRiegoManual.setText("Detener Riego");
        btnDetenerRiegoManual.addActionListener(this::btnDetenerRiegoManualActionPerformed);

        btnIniciarRiegoManual.setText("Iniciar Riego");
        btnIniciarRiegoManual.addActionListener(this::btnIniciarRiegoManualActionPerformed);

        btnVolverAlMenu.setText("Volver al Menú");
        btnVolverAlMenu.addActionListener(this::btnVolverAlMenuActionPerformed);

        btnConectar.setText("Conectar");
        btnConectar.addActionListener(this::btnConectarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 194, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnIniciarRiegoManual)
                        .addGap(104, 104, 104)
                        .addComponent(btnDetenerRiegoManual)
                        .addGap(232, 232, 232))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVolverAlMenu)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnConectar)
                        .addGap(82, 82, 82))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(btnConectar)
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetenerRiegoManual)
                    .addComponent(btnIniciarRiegoManual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addComponent(btnVolverAlMenu)
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverAlMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAlMenuActionPerformed
        // TODO add your handling code here:
        
        
        
        
        FrmMenu menu = new FrmMenu();
        
        menu.setVisible(true);
        this.setVisible(false);
    }

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        String puerto = JOptionPane.showInputDialog("Indique el puerto (Ej: COM3):");


        if (puerto == null || puerto.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Operación cancelada o puerto inválido.");
            return;
        }

        boolean conectado = conectarESP32.ejecutar(puerto);

        if (!conectado) {
            JOptionPane.showMessageDialog(this, "Error: No se pudo abrir el puerto " + puerto + ". Verifica que no esté en uso.");
            return;
        }

        JOptionPane.showMessageDialog(this, "¡Conectado exitosamente al ESP32!");
        
        
        btnIniciarRiegoManual.setEnabled(true);
        btnDetenerRiegoManual.setEnabled(true);
        

        btnConectar.setEnabled(false);
        btnConectar.setText("Conectado");
        
    }                                           

    private void btnIniciarRiegoManualActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        
        
        String resultado = iniciarRiego.ejecutar();
        
        JOptionPane.showMessageDialog(this, resultado);
        
        
    }                                                     

    private void btnDetenerRiegoManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetenerRiegoManualActionPerformed
        // TODO add your handling code here:
        
        
        String resultado = detenerRiego.ejecutar();

        JOptionPane.showMessageDialog(this, resultado);
    }//GEN-LAST:event_btnDetenerRiegoManualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPanelRiegoManual().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnDetenerRiegoManual;
    private javax.swing.JButton btnIniciarRiegoManual;
    private javax.swing.JButton btnVolverAlMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
